# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/ai/Downloads/crypto/lib/cryptanalysislib;/home/ai/Downloads/crypto/lib/cryptanalysislib/build-dev")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "maintainer@reflectcpp.org")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/nix/store/hkldf6z3rlgdrkza4avb5r4hplr4kfa0-cmake-4.1.6/share/cmake-4.1/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "CryptanalysisLib built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ;RPM;DEB")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/ai/Downloads/crypto/lib/cryptanalysislib/build-dev;CryptanalysisLib;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "reflectcpp 0.25.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "reflectcpp 0.25.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/nix/store/c8f95avghs0b8m3vzvqc4fn9q058h7qp-llvm-21.1.8/bin/llvm-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/nix/store/c8f95avghs0b8m3vzvqc4fn9q058h7qp-llvm-21.1.8/bin/llvm-objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/ai/Downloads/crypto/lib/cryptanalysislib/build-dev/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "maintainer@reflectcpp.org")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/ai/Downloads/crypto/lib/cryptanalysislib/build-dev/_deps/reflect-cpp-src/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Reflect C++ library")
set(CPACK_PACKAGE_FILE_NAME "reflectcpp-0.25.0-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "reflectcpp 0.25.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "reflectcpp 0.25.0")
set(CPACK_PACKAGE_NAME "reflectcpp")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Reflect C++ Team")
set(CPACK_PACKAGE_VERSION "0.25.0")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "25")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/nix/store/c8f95avghs0b8m3vzvqc4fn9q058h7qp-llvm-21.1.8/bin/llvm-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/ai/Downloads/crypto/lib/cryptanalysislib/build-dev/_deps/reflect-cpp-src/LICENSE")
set(CPACK_RESOURCE_FILE_README "/nix/store/hkldf6z3rlgdrkza4avb5r4hplr4kfa0-cmake-4.1.6/share/cmake-4.1/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/nix/store/hkldf6z3rlgdrkza4avb5r4hplr4kfa0-cmake-4.1.6/share/cmake-4.1/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_REQUIRES "")
set(CPACK_RPM_PACKAGE_URL "https://rfl.getml.com")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/ai/Downloads/crypto/lib/cryptanalysislib/build-dev/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/ai/Downloads/crypto/lib/cryptanalysislib/build-dev/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
