name: arm

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pguyot/arm-runner-action@HEAD
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a53
        commands: |
            # sudo apt-get install -y libmpfr-dev libpng-dev libtbb-dev
            sudo apt install -y cmake make
            git clone --depth=1 --single-branch --branch v1.7.1 https://github.com/google/benchmark.git benchmark && mkdir -p benchmark/build && cd ./benchmark/build &&  cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_GTEST_TESTS=OFF ../ && make -j
            sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/libgtest.a /usr/lib  && sudo cp lib/libgtest_main.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
            cmake --build ${{github.workspace}}/build --config Debug
            ./build.sh
            cmake --build ${{github.workspace}}/build --config Debug
            cd build
            ./tests/test_build_tree
            test `uname -m` = 'aarch64'
