name: Test aarch64 cpu option

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pguyot/arm-runner-action@HEAD
      with:
        base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bullseye.7z
        cpu: cortex-a53
        commands: |
            # sudo apt-get install -y libmpfr-dev libpng-dev libtbb-dev
            git clone --depth=1 --single-branch --branch v1.7.1 https://github.com/google/benchmark.git benchmark && mkdir -p benchmark/build && cd ./benchmark/build &&  cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_GTEST_TESTS=OFF ../ && make -j
            sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/libgtest.a /usr/lib  && sudo cp lib/libgtest_main.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
            cmake --build ${{github.workspace}}/build --config Debug
            ./build.sh
            cmake --build ${{github.workspace}}/build --config Debug
            cd build
            ./tests/test_build_tree
            test `uname -m` = 'aarch64'

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        arch: [armv6l, armv7l, aarch64]
#        include:
#        - arch: armv6l
#          cpu: arm1176
#          base_image: raspios_lite:latest
#        - arch: armv7l
#          cpu: cortex-a7
#          base_image: raspios_lite:latest
#        - arch: aarch64
#          cpu: cortex-a53
#          base_image: raspios_lite_arm64:latest
#
#    steps:
#      - uses: actions/checkout@v4:with
#    - uses: pguyot/arm-runner-action@v2.5.2
#      id: build_image
#      with:
#        base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bullseye.7z
#        cpu: cortex-a53
#        commands: |
#          git clone --depth=1 --single-branch --branch v1.7.1 https://github.com/google/benchmark.git benchmark && mkdir -p benchmark/build && cd ./benchmark/build &&  cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_GTEST_TESTS=OFF ../ && make -j
#          sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/libgtest.a /usr/lib  && sudo cp lib/libgtest_main.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
#          cmake --build ${{github.workspace}}/build --config Debug
#          ./build.sh
#          cmake --build ${{github.workspace}}/build --config Debug
#          cd build
#          ./tests/test_build_tree
#
