name: arm

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: pguyot/arm-runner-action@HEAD
      with:
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a53
        commands: |
            sudo apt-get install -y cmake make git
            git clone --depth=1 --single-branch --branch v1.7.1 https://github.com/google/benchmark.git benchmark && mkdir -p benchmark/build && cd ./benchmark/build &&  cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_GTEST_TESTS=OFF ../ && make -j
            sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/libgtest.a /usr/lib  && sudo cp lib/libgtest_main.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
            # cd ${{github.workspace}}
            echo $(pwd)
            git submodule init
            git submodule update --recursive --init
            mkdir -p build
            mkdir -p cmake-build-release
            mkdir -p cmake-build-debug
            chmod +x ./build.sh
            ./build.sh
            cd build
            cmake ..
            make
            ./tests/test_build_tree
            test `uname -m` = 'aarch64'
