name: ubuntu_x86_perf

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        version: [ 18 ]
        build_type: [Release ]

    name: Build & test on ${{ matrix.os }} with clang-${{ matrix.version }} in ${{ matrix.build_type }} mode.
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Install Software
      run: |
        sudo apt-get update
        sudo apt-get install -y libtbb-dev clang-${{matrix.version}} libomp-${{matrix.version}}-dev libpfm4-dev libgtest-dev
        sudo apt-get install -y linux-tools-common linux-tools-$(uname -r)
        sudo sh -c 'echo -1 >/proc/sys/kernel/perf_event_paranoid'

    - name: Install Google Benchmark
      run: |
        git clone --depth=1 --single-branch --branch v1.9.5 https://github.com/google/benchmark.git
        cd benchmark
        cmake -E make_directory "build"
        cmake -E chdir "build" cmake -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DBENCHMARK_ENABLE_LIBPFM=on -DCMAKE_BUILD_TYPE=Release ../
        # Perform system-wide installation of header and built library
        sudo cmake --build "build" --config Release --target install -j

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=clang++-${{matrix.version}} -G "Unix Makefiles"

    - name: Build
      working-directory: ${{github.workspace}}/build
      # run: make bench_nn_benchmark
      run: make -j$(nproc) test_sort_sorting_algorithms

    - name: Bench
      working-directory: ${{github.workspace}}/build
      run: |
        perf list
        perf record -o perf.data --call-graph fp --freq=max ./tests/sort/test_sort_sorting_algorithms
        perf script -i perf.data  --full-source-path --call-ret-trace -F +pid >> ${{github.workspace}}/build/perf.out

    - name: save perf.data
      uses: actions/upload-artifact@v7
      with:
        name: perf-report
        path: ${{github.workspace}}/build/perf.out
