name: ubuntu_x86_tracy

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        version: [ 18 ]
        build_type: [Release ]

    name: Build & test on ${{ matrix.os }} with clang-${{ matrix.version }} in ${{ matrix.build_type }} mode.
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Install Software
      run: |
        sudo apt-get update
        sudo apt-get install -y libtbb-dev clang-${{matrix.version}} libomp-${{matrix.version}}-dev libgtest-dev libbenchmark-dev

    - name: Build Tracy
      run: |
        sudo apt-get install -y pkg-config libfreetype-dev libdbus-1-dev
        # must match the GIT_TAG of the tracy client in CMakeLists.txt
        git clone --depth=1 --single-branch --branch v0.14.1 https://github.com/wolfpld/tracy/
        cd tracy
        cmake -B capture/build -S capture -DCMAKE_BUILD_TYPE=Release
        cmake --build capture/build --parallel --config Release

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=clang++-${{matrix.version}} -G "Unix Makefiles" -DUSE_TRACY=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      # run: make bench_nn_benchmark
      run: make -j$(nproc) test_sort_sorting_algorithms

    - name: Bench
      working-directory: ${{github.workspace}}/build
      run: |
        ${{github.workspace}}/tracy/capture/build/tracy-capture -o out.tracy -a 127.0.0.1 -s 20 &
        ./tests/sort/test_sort_sorting_algorithms
        sleep 20

    - name: save tracy output
      uses: actions/upload-artifact@v7
      with:
        name: tracy-report
        path: ${{github.workspace}}/build/out.tracy
