name: ubuntu_x86_perf

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        version: [ 15 ]
        build_type: [Release ]

    name: Build & test on ${{ matrix.os }} with clang-${{ matrix.version }} in ${{ matrix.build_type }} mode.
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Software
      run: |
        sudo apt-get install -y libtbb-dev clang-${{matrix.version}}
        sudo apt-get install -y libomp-${{matrix.version}}-dev libomp5-${{matrix.version}}
        sudo apt-get install -y linux-tools-generic

    - name: Install Google Benchmark
      run: git clone --depth=1 --single-branch --branch v1.7.1 https://github.com/google/benchmark.git benchmark && mkdir -p benchmark/build && cd ./benchmark/build &&  cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_GTEST_TESTS=OFF ../ && make -j

    - name: Install gtest
      run:
        sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/libgtest.a /usr/lib  && sudo cp lib/libgtest_main.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a


    - name: Configure CMake
      env:
        CXX: clang++-${{ matrix.compiler }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=clang++-${{matrix.version}}

    - name: Build
      run: make bench_nn_benchmark

    - name: Bench
      working-directory: ${{github.workspace}}/build
      run: perf record -F ./bench/nn/bench_nn_bruteforce
